[package]
name = "coinbase-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
demand-easy-sv2 = {version="0.2.0",git="https://github.com/demand-open-source/demand-easy-sv2"}
tokio = {version="1.36.0",features = ["full","tracing"]}
dotenv = "0.15.0"
bitcoin = "0.32.0"
